name: pet_style
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  flutter_localizations: 
    sdk: flutter  
  
  # Internet connection check
  internet_connection_checker_plus: ^2.4.1

  searchfield: ^1.0.5

  # bloc
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  flutter_screenutil: ^5.9.3

  smooth_page_indicator: ^1.1.0
  flutter_svg: ^2.0.10

  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  get_it: ^7.7.0
  go_router: ^14.1.4
  badges: ^3.1.2
  google_fonts: ^6.2.1


  fluttertoast: ^8.2.6
  
  animated_splash_screen: ^1.3.0
  lottie: ^3.1.2

  shared_preferences: ^2.2.3

  cached_network_image: ^3.3.1
  image_picker: ^1.1.2

  dio: ^5.4.3

  firebase_core: ^2.32.0
  cloud_firestore: ^4.17.5

  #logger
  talker: 4.2.3
  talker_flutter: ^4.2.3
  talker_dio_logger: ^4.2.3
  talker_bloc_logger: ^4.2.3
  
  #auth
  google_sign_in: ^6.2.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0

  date_picker_timeline: ^1.2.6
  pinput: ^5.0.0
  
  http_parser: ^4.0.2

  animate_do: ^3.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.10
  freezed: ^2.5.2
  json_serializable: ^6.8.0

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/lottie/
    - assets/json/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
