// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIW87jgtPcacZCYMGFajZPW_t3A-uhWJM',
    appId: '1:938733879715:web:60bd6b18d9c39298d19a16',
    messagingSenderId: '938733879715',
    projectId: 'pet-style-md',
    authDomain: 'pet-style-md.firebaseapp.com',
    storageBucket: 'pet-style-md.appspot.com',
    measurementId: 'G-BKNCLJNP1F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS0nex8fjyYv_VYcRPSWrAjtnJzCKGaIw',
    appId: '1:938733879715:android:8759531a28421c7dd19a16',
    messagingSenderId: '938733879715',
    projectId: 'pet-style-md',
    storageBucket: 'pet-style-md.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZCEhppjgqUeuddPkpuKHD_x4MHTOIIoM',
    appId: '1:938733879715:ios:c5b8227493dad90ad19a16',
    messagingSenderId: '938733879715',
    projectId: 'pet-style-md',
    storageBucket: 'pet-style-md.appspot.com',
    androidClientId: '938733879715-6u4mohkcigje5b29p5rhou8j9rvflpla.apps.googleusercontent.com',
    iosClientId: '938733879715-e4dfd9q997lfu6apvpkb50hu535jdgrs.apps.googleusercontent.com',
    iosBundleId: 'dev.dextermd.petstyle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZCEhppjgqUeuddPkpuKHD_x4MHTOIIoM',
    appId: '1:938733879715:ios:c5b8227493dad90ad19a16',
    messagingSenderId: '938733879715',
    projectId: 'pet-style-md',
    storageBucket: 'pet-style-md.appspot.com',
    androidClientId: '938733879715-6u4mohkcigje5b29p5rhou8j9rvflpla.apps.googleusercontent.com',
    iosClientId: '938733879715-e4dfd9q997lfu6apvpkb50hu535jdgrs.apps.googleusercontent.com',
    iosBundleId: 'dev.dextermd.petstyle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIW87jgtPcacZCYMGFajZPW_t3A-uhWJM',
    appId: '1:938733879715:web:558bdede524efe15d19a16',
    messagingSenderId: '938733879715',
    projectId: 'pet-style-md',
    authDomain: 'pet-style-md.firebaseapp.com',
    storageBucket: 'pet-style-md.appspot.com',
    measurementId: 'G-1WCSD7HCBT',
  );

}